ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = ~/.arduino-makefile
BOARD_TAG = uno
ARCHITECTURE  = avr
MONITOR_PORT  = /dev/ttyUSB0
AVRDUDE_CONF = /usr/share/arduino/hardware/tools/avrdude.conf

ARDUINO_LIBS = Wire LiquidCrystal_I2C RTClib TEA5767 elapsedMillis Adafruit_BusIO SPI

OPTIMIZATION_LEVEL=s

include $(ARDMK_DIR)/Arduino.mk
